=== uo301299/MotoGP-Desktop-Usabilidad/MotoGP-Desktop/xml/circuito.dtd
<!ELEMENT circuito (nombre, dimensiones, fecha, hora_inicio, vueltas, ubicacion, 
            patrocinador, referencias, galeria_fotos, galeria_videos, geografia, 
            tramos, resultados, clasificacion_mundial)>

<!ELEMENT nombre (#PCDATA)>


<!ELEMENT dimensiones (longitud, anchura)>
<!ELEMENT longitud (#PCDATA)>
<!ATTLIST longitud unidad CDATA #REQUIRED>
<!ELEMENT anchura (#PCDATA)>
<!ATTLIST anchura unidades (m) "m">


<!ELEMENT fecha (#PCDATA)>
<!ATTLIST fecha formato CDATA "YYYY-MM-DD">


<!ELEMENT hora_inicio (#PCDATA)>
<!ATTLIST hora_inicio zona CDATA "Europe/Madrid">

<!ELEMENT vueltas (#PCDATA)>


<!ELEMENT ubicacion (localidad, pais)>
<!ELEMENT localidad (#PCDATA)>
<!ELEMENT pais (#PCDATA)>

<!ELEMENT patrocinador (#PCDATA)>


<!ELEMENT referencias (referencia, referencia, referencia, referencia*)>
<!ELEMENT referencia (#PCDATA)>
<!ATTLIST referencia tipo (web|libro|articulo|video|otro) "web"
                   url  CDATA #IMPLIED>


<!ELEMENT galeria_fotos (foto, foto, foto)>
<!ELEMENT foto (#PCDATA)>
<!ATTLIST foto archivo CDATA #REQUIRED
               titulo  CDATA #IMPLIED>


<!ELEMENT galeria_videos (video, video)>
<!ELEMENT video (#PCDATA)>
<!ATTLIST video archivo CDATA #REQUIRED
                 titulo  CDATA #IMPLIED>
               

<!ELEMENT geografia (origen)>
<!ELEMENT origen (longitud, latitud, altitud)>
<!ELEMENT latitud (#PCDATA)>
<!ATTLIST latitud unidad CDATA #REQUIRED>
<!ELEMENT altitud (#PCDATA)>
<!ATTLIST altitud unidad CDATA #REQUIRED>


<!ELEMENT tramos (tramo+)>
<!ELEMENT tramo (distancia, puntoFinal, sector)>
<!ELEMENT distancia (#PCDATA)>
<!ATTLIST distancia unidad CDATA #REQUIRED>
<!ELEMENT puntoFinal (longitud, latitud, altitud)>
<!ELEMENT sector (#PCDATA)>


<!ELEMENT resultados (vencedor)>
<!ELEMENT vencedor EMPTY>
<!ATTLIST vencedor nombre CDATA #REQUIRED
                   tiempo CDATA #REQUIRED>


<!ELEMENT clasificacion_mundial (piloto, piloto, piloto)>
<!ELEMENT piloto (#PCDATA)>
<!ATTLIST piloto pos    (1|2|3) #REQUIRED
                 puntos CDATA   #IMPLIED>

=== uo301299/MotoGP-Desktop-Usabilidad/MotoGP-Desktop/xml/circuito.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE circuito SYSTEM "circuito.dtd">

<circuito>
  <nombre>TT Circuit Assen</nombre>

  <dimensiones>
    <longitud unidad="m">4555</longitud>
    <anchura unidades="m">14</anchura>
  </dimensiones>

  <fecha formato="YYYY-MM-DD">2025-06-29</fecha>

  <hora_inicio zona="Europe/Madrid">14:00</hora_inicio>

  <vueltas>26</vueltas>

  <ubicacion>
    <localidad>Assen</localidad>
    <pais>Países Bajos</pais>
  </ubicacion>

  <patrocinador>TABAC Fragances</patrocinador>

  <referencias>
    <referencia tipo="web" url="https://www.ttcircuit.com/en">Web oficial TT Circuit Assen</referencia>
    <referencia tipo="web" url="https://es.wikipedia.org/wiki/Circuito_de_Assen">Wikipedia de TT Circuit Assen</referencia>
    <referencia tipo="web" url="https://www.motogp.com/es">Web oficial de MotoGP</referencia>
  </referencias>

  <galeria_fotos>
    <foto archivo="./multimedia/Panorama.jpg">Panorámica del circuito</foto>
    <foto archivo="./multimedia/RectaMeta.jpg">Recta de meta</foto>
    <foto archivo="./multimedia/EsquemaRecorrido.jpg">Esquema del TT Circuit Assen</foto>
  </galeria_fotos>

  <galeria_videos>
    <video archivo="./multimedia/GoProVuelta.mp4">GoPro  vuelta al Circuito Assen</video>
    <video archivo="./multimedia/PedrosaAnalizaAssen.mp4">Analisis del circuito por Pedrosa</video>
  </galeria_videos>

  <geografia>
    <origen>
      <longitud unidad="deg">6.5240992</longitud>
      <latitud unidad="deg">52.9623206</latitud>
      <altitud unidad="m">11.9768761</altitud>
    </origen>
  </geografia>

  <tramos>
    <tramo>
      <distancia unidad="m">391.95</distancia>
      <puntoFinal>
        <longitud unidad="deg">6.5286640</longitud>
        <latitud unidad="deg">52.9645534</latitud>
        <altitud unidad="m">11.9769228</altitud>
      </puntoFinal>
      <sector>1</sector>
    </tramo>

    <tramo>
      <distancia unidad="m">50.32</distancia>
      <puntoFinal>
        <longitud unidad="deg">6.5293506</longitud>
        <latitud unidad="deg">52.9645932</latitud>
        <altitud unidad="m">11.9769238</altitud>
      </puntoFinal>
      <sector>1</sector>
    </tramo>

    <tramo>
      <distancia unidad="m">129.8</distancia>
      <puntoFinal>
        <longitud unidad="deg">6.5308586</longitud>
        <latitud unidad="deg">52.9638535</latitud>
        <altitud unidad="m">10.7715270</altitud>
      </puntoFinal>
      <sector>1</sector>
    </tramo>

    <tramo>
      <distancia unidad="m">23.18</distancia>
      <puntoFinal>
        <longitud unidad="deg">6.5309934</longitud>
        <latitud unidad="deg">52.9636577</latitud>
        <altitud unidad="m">10.5190337</altitud>
      </puntoFinal>
      <sector>1</sector>
    </tramo>

    <tramo>
      <distancia unidad="m">138.77</distancia>
      <puntoFinal>
        <longitud unidad="deg">6.5312317</longitud>
        <latitud unidad="deg">52.9623960</latitud>
        <altitud unidad="m">10.2947784</altitud>
      </puntoFinal>
      <sector>1</sector>
    </tramo>

    <tramo>
      <distancia unidad="m">99.12</distancia>
      <puntoFinal>
        <longitud unidad="deg">6.5302558</longitud>
        <latitud unidad="deg">52.9619153</latitud>
        <altitud unidad="m">11.1429403</altitud>
      </puntoFinal>
      <sector>1</sector>
    </tramo>

    <tramo>
      <distancia unidad="m">116.31</distancia>
      <puntoFinal>
        <longitud unidad="deg">6.5293496</longitud>
        <latitud unidad="deg">52.9626228</latitud>
        <altitud unidad="m">10.2945296</altitud>
      </puntoFinal>
      <sector>1</sector>
    </tramo>

    <tramo>
      <distancia unidad="m">53.27</distancia>
      <puntoFinal>
        <longitud unidad="deg">6.5298311</longitud>
        <latitud unidad="deg">52.9631322</latitud>
        <altitud unidad="m">10.2947392</altitud>
      </puntoFinal>
      <sector>1</sector>
    </tramo>

    <tramo>
      <distancia unidad="m">70.43</distancia>
      <puntoFinal>
        <longitud unidad="deg">6.5292491</longitud>
        <latitud unidad="deg">52.9634862</latitud>
        <altitud unidad="m">10.5437092</altitud>
      </puntoFinal>
      <sector>1</sector>
    </tramo>

    <tramo>
      <distancia unidad="m">752.19</distancia>
      <puntoFinal>
        <longitud unidad="deg">6.5232596</longitud>
        <latitud unidad="deg">52.9577847</latitud>
        <altitud unidad="m">11.0388853</altitud>
      </puntoFinal>
      <sector>1</sector>
    </tramo>

    <tramo>
      <distancia unidad="m">73.73</distancia>
      <puntoFinal>
        <longitud unidad="deg">6.5222185</longitud>
        <latitud unidad="deg">52.9576371</latitud>
        <altitud unidad="m">11.7832754</altitud>
      </puntoFinal>
      <sector>1</sector>
    </tramo>

    <tramo>
      <distancia unidad="m">116.48</distancia>
      <puntoFinal>
        <longitud unidad="deg">6.5210422</longitud>
        <latitud unidad="deg">52.9568915</latitud>
        <altitud unidad="m">11.0388376</altitud>
      </puntoFinal>
      <sector>1</sector>
    </tramo>

    <tramo>
      <distancia unidad="m">189.9</distancia>
      <puntoFinal>
        <longitud unidad="deg">6.5208849</longitud>
        <latitud unidad="deg">52.9551746</latitud>
        <altitud unidad="m">10.7730221</altitud>
      </puntoFinal>
      <sector>2</sector>
    </tramo>

    <tramo>
      <distancia unidad="m">93.3</distancia>
      <puntoFinal>
        <longitud unidad="deg">6.5197539</longitud>
        <latitud unidad="deg">52.9547307</latitud>
        <altitud unidad="m">11.7832130</altitud>
      </puntoFinal>
      <sector>2</sector>
    </tramo>

    <tramo>
      <distancia unidad="m">381.89</distancia>
      <puntoFinal>
        <longitud unidad="deg">6.5145228</longitud>
        <latitud unidad="deg">52.9546967</latitud>
        <altitud unidad="m">11.2931054</altitud>
      </puntoFinal>
      <sector>2</sector>
    </tramo>

    <tramo>
      <distancia unidad="m">67.48</distancia>
      <puntoFinal>
        <longitud unidad="deg">6.5137464</longitud>
        <latitud unidad="deg">52.9543636</latitud>
        <altitud unidad="m">11.6052104</altitud>
      </puntoFinal>
      <sector>2</sector>
    </tramo>

    <tramo>
      <distancia unidad="m">140.09</distancia>
      <puntoFinal>
        <longitud unidad="deg">6.5133329</longitud>
        <latitud unidad="deg">52.9530914</latitud>
        <altitud unidad="m">12.1553260</altitud>
      </puntoFinal>
      <sector>2</sector>
    </tramo>

    <tramo>
      <distancia unidad="m">142.25</distancia>
      <puntoFinal>
        <longitud unidad="deg">6.5117930</longitud>
        <latitud unidad="deg">52.9530290</latitud>
        <altitud unidad="m">12.5883415</altitud>
      </puntoFinal>
      <sector>2</sector>
    </tramo>

    <tramo>
      <distancia unidad="m">154.65</distancia>
      <puntoFinal>
        <longitud unidad="deg">6.5113293</longitud>
        <latitud unidad="deg">52.9542656</latitud>
        <altitud unidad="m">12.4618869</altitud>
      </puntoFinal>
      <sector>2</sector>
    </tramo>
    
    <tramo>
      <distancia unidad="m">176.27</distancia>
      <puntoFinal>
        <longitud unidad="deg">6.5127869</longitud>
        <latitud unidad="deg">52.9556032</latitud>
        <altitud unidad="m">11.7831684</altitud>
      </puntoFinal>
      <sector>2</sector>
    </tramo>

    <tramo>
      <distancia unidad="m">71.89</distancia>
      <puntoFinal>
        <longitud unidad="deg">6.5135661</longitud>
        <latitud unidad="deg">52.9560541</latitud>
        <altitud unidad="m">11.7832751</altitud>
      </puntoFinal>
      <sector>3</sector>
    </tramo>

    <tramo>
      <distancia unidad="m">242.13</distancia>
      <puntoFinal>
        <longitud unidad="deg">6.5168433</longitud>
        <latitud unidad="deg">52.9569736</latitud>
        <altitud unidad="m">11.4335562</altitud>
      </puntoFinal>
      <sector>3</sector>
    </tramo>

    <tramo>
      <distancia unidad="m">72.77</distancia>
      <puntoFinal>
        <longitud unidad="deg">6.5178955</longitud>
        <latitud unidad="deg">52.9571151</latitud>
        <altitud unidad="m">11.3793142</altitud>
      </puntoFinal>
      <sector>3</sector>
    </tramo>

    <tramo>
      <distancia unidad="m">91.84</distancia>
      <puntoFinal>
        <longitud unidad="deg">6.5192118</longitud>
        <latitud unidad="deg">52.9573192</latitud>
        <altitud unidad="m">11.4331006</altitud>
      </puntoFinal>
      <sector>3</sector>
    </tramo>

    <tramo>
      <distancia unidad="m">77.18</distancia>
      <puntoFinal>
        <longitud unidad="deg">6.5202202</longitud>
        <latitud unidad="deg">52.9576628</latitud>
        <altitud unidad="m">11.4336622</altitud>
      </puntoFinal>
      <sector>3</sector>
    </tramo>

    <tramo>
      <distancia unidad="m">136.57</distancia>
      <puntoFinal>
        <longitud unidad="deg">6.5212345</longitud>
        <latitud unidad="deg">52.9586697</latitud>
        <altitud unidad="m">11.4333606</altitud>
      </puntoFinal>
      <sector>3</sector>
    </tramo>

    <tramo>
      <distancia unidad="m">210.2</distancia>
      <puntoFinal>
        <longitud unidad="deg">6.5213773</longitud>
        <latitud unidad="deg">52.9605739</latitud>
        <altitud unidad="m">11.4283005</altitud>
      </puntoFinal>
      <sector>3</sector>
    </tramo>

    <tramo>
      <distancia unidad="m">56.41</distancia>
      <puntoFinal>
        <longitud unidad="deg">6.5218351</longitud>
        <latitud unidad="deg">52.9609080</latitud>
        <altitud unidad="m">11.4283005</altitud>
      </puntoFinal>
      <sector>3</sector>
    </tramo>
